### ISSUE TITLE
Recursion in CDBResult class>>#fromDictionary:

### ISSUE THREAD

**Issue by astares** [Mr-Dispatch/pharo-cozodb#1]
- CDBResultSet inherits from CBDResult and does not implement #fromDictionary:

so the code in CDBResult class>>#fromDictionary:

```Smalltalk
fromDictionary: dict

	^ ((dict at: #ok)
		   ifTrue: [ CDBResultSet ]
		   ifFalse: [ CDBErrorResult ]) fromDictionary: dict
```
leads to a **recursion:** when #ok is flagged in the dict then CDBResultSet is picked as the class and again #fromDictionary: is sent which is again found in the superclass CDBResult class>>#fromDictionary:

You can already reproduce with Pharo 11 or 12 and the sample given in the README

**Comment by Mr-Dispatch** [comment]
Refactor till death ;-) Or: True, oh so true.

I wanted the trait-introduced functionality to be inherited, and didn't realize the  pre-existing constructor method broke it.

Instead of using the trait in subclasses, I decided to rename the factory method to `fromResponse:`, as the cozo response is pretty specific dict anyways.

Fix incoming.

**Comment by Mr-Dispatch** [comment]
Message to self: although the method was deleted, is still shows in search under original class with original text. Pinpoint & create issue.
